spring:
  application:
    name: hire-car
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'postgres'
    password: '56657131'
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
springdoc:
  api-docs:
    path: '/api-docs'
